
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgfhmmseeqybpwjpgcqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnZmhtbXNlZXF5YnB3anBnY3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTU3NDIsImV4cCI6MjA2MzA3MTc0Mn0.K684JXZHwJowOVipRMRXS5LsAiIBCnHn_e1y1qZg92o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
